version: '3.8'

networks:
  app_network:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

  db:
    image: postgres:16
    restart: always
    hostname: postgres
    env_file:
      - './server/.env'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - './server/.env'
    ports:
      - "4000:4000"
    networks:
      - app_network
    depends_on:
      - db
    command: >
      sh -c "
      until nc -z db 5432; do
        echo 'Waiting for the database to be ready...';
        sleep 2;
      done;
      npx prisma migrate deploy &&
      npm start
      "

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    env_file:
      - './client/.env'
    ports:
      - "3000:80"
    networks:
      - app_network

volumes:
  postgres_data: