ALTER TABLE "chats" ADD COLUMN "userId" INTEGER DEFAULT 1;
UPDATE "chats" SET "userId" = 1 WHERE "userId" IS NULL;

ALTER TABLE "chats" ALTER COLUMN "userId" DROP DEFAULT;
ALTER TABLE "chats" ALTER COLUMN "userId" SET NOT NULL;

ALTER TABLE "chats" ADD CONSTRAINT "chats_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;